export const AUTHENTICATE = "AUTHENTICATE";
export const AUTH_ERROR = "AUTH_ERROR";
export const SET_LOADING = "SET_LOADING";

export const CREATE_GUILD = "CREATE_GUILD";
export const GUILD_ERROR = "GUILD_ERROR";
export const GET_USER_GUILDS = "GET_USER_GUILDS";
export const GET_GUILD_BY_ID = "GET_GUILD_BY_ID";

export const GET_CHANNEL_BY_ID = "GET_CHANNEL_BY_ID";
export const UPDATE_CHANNEL_BY_ID = "UPDATE_CHANNEL_BY_ID";
export const CHANNEL_ERROR = "CHANNEL_ERROR";
export const CREATE_CHANNEL = "CREATE_CHANNEL";
